server:
    error:
        include-message: always
spring:
    data:
        mongodb:
            uri: ${MONGO_DB_CONNECTION}
            database: ${MONGO_DB_DATABASE}

bot:
    token: ${BOT_TOKEN}
    openAIApiKey: ${OPENAI_API_KEY}
